{% set python_min = "3.11" %}
{% set name = "nionswift-experimental" %}
{% set version = "0.7.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 60e72795032c657c5d23c6e3efd24486b437614b46a4356f84c778748603c20e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - nionswift >=16.12,<17.0
    - nionui >=8.0,<9.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - nionswift_plugin.nion_experimental_4dtools
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Experimental tools package for Nion Swift.
  dev_url: https://github.com/nion-software/experimental

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
