{% set name = "nionswift-experimental" %}
{% set version = "0.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebe7e2f811f4e17b29274a6c1aeef61f3fe72d5f537161b1f253d6f934bec8d1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - nionswift >=16.9.0,<17.0.0
    - nionui >=7.0.0,<8.0.0

test:
  imports:
    - nionswift_plugin.nion_experimental_4dtools
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Experimental tools package for Nion Swift.
  dev_url: https://github.com/nion-software/experimental

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
