{% set name = "nionswift-experimental" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a444a31c0dfa124b4b1a6bd0383e2bee96e025512c14f98cbe6cfc88368f88b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - nionswift >=0.15.0,<0.16.0
    - python >=3.7

test:
  imports:
    - nionswift_plugin.nion_experimental_4dtools
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Experimental tools package for Nion Swift.
  dev_url: https://github.com/nion-software/experimental

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
