{% set name = "nionswift-experimental" %}
{% set version = "0.7.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d1bed69b862552b5a64ffd165facd19f15fce3441127f1e6a2cb181d34acb1e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools
  run:
    - python >=3.11
    - nionswift >=16.12,<17.0
    - nionui >=8.0,<9.0

test:
  imports:
    - nionswift_plugin.nion_experimental_4dtools
    - nionswift_plugin.nion_experimental_tools

about:
  home: https://github.com/nion-software/experimental
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Experimental tools package for Nion Swift.
  dev_url: https://github.com/nion-software/experimental

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
